default_context:
  name: "agentflow"
  version: "0.1.0"
  slug: "agentflow"
  command: "agentflow"
  cli: "argparse"
  compat: "upyog"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  description: "Yet Another Agent Framework"
  author: "Achilles Gasper Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "yet another agent framework"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "agentflow"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "agentflow"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/agentflow"