default_context:
  name: "agentflow"
  version: "0.1.0"
  slug: "agentflow"
  command: "agentflow"
  cli: "argparse"
  compat: "upyog"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  description: "Agentflow is a simple, yet powerful agentic framework, built for humans."
  author: "Achilles Gasper Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "agentflow"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "okooai"
  repo_service_reponame: "agentflow"
  docker_service_username: "okooai"
  docker_service_reponame: "agentflow"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/okooai/Agentflow"